workflows:
  python-build:
    name: Amiral Titan APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Install Buildozer and Dependencies
        script: |
          pip install buildozer
          pip install pandas kivy
      - name: Build APK
        script: |
          # Cette commande va lancer la compilation lourde que ton téléphone ne pouvait pas faire
          yes | buildozer android debug
    artifacts:
      - bin/*.apk
