workflows:
  python-build:
    name: Amiral Titan APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Install Buildozer and Dependencies
        script: |
          # Correction pour Python 3.12
          pip install --upgrade pip
          pip install setuptools
          pip install buildozer
          pip install pandas kivy
      - name: Build APK
        script: |
          # On s'assure que buildozer.spec existe, sinon on le génère
          if [ ! -f buildozer.spec ]; then buildozer init; fi
          yes | buildozer android debug
    artifacts:
      - bin/*.apk
