workflows:
  python-build:
    name: Amiral Titan APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Install Buildozer and Dependencies
        script: |
          # Installation des outils de base pour Python 3.12
          pip install --upgrade pip
          pip install setuptools cython==0.29.33 virtualenv
          pip install buildozer
          pip install pandas kivy
      - name: Build APK
        script: |
          # Initialisation automatique si nécessaire
          if [ ! -f buildozer.spec ]; then buildozer init; fi
          # Lancement de la compilation
          yes | buildozer android debug
    artifacts:
      - bin/*.apk
